Friends/sriaman.html
Just created a sriaman.html file .
=> sriaman.html

Friends/izumemori.html
=> add my depressing site

Friends/qoyyuum.html
=> Created qoyyuum.html

Friends/yugenchokshi.html
I am here to make friends at Hacktober2018 ;) 
" **Added my .html file to friends with friendly content in it** "
=> Added my .html file to friends with friendly content in it

Friends/connorocampo.html
https://github.com/connorocampo
=> Added username

Friends/ChameeraD.html
=> profile added

Friends/minnimimi.html
=> minnimimi simple website

Friends/pixelinc.html
=> Create an awesome page you could probably live without.

Friends/Gladson9.html
Added my profile .
can we be friends?
=> Added Gladson9 profile

Friends/riyabhatia26.html
Introduced myself, added link to my profiles.
=> Introduced myself in riyabhatia26.html

Friends/nrsalmon.html
of course I forgot to checkout my own branch but please be forgiving, it's my very first pull request on github!!!
=> created my own page!

Friends/SrVladyslav.HTML
=> Adding Vladyslav's html

Friends/Drakantas.html
=> what's up my dudes

Friends/Enra.html, Friends/sr229.html
=> Happy Hacktoberfest

Friends/nickxla.html
Cheers and good luck for Hacktoberfest 2018 ! 🚀🎃
=> Added nickxla page :shipit:

Friends/syauqiahmd.html
=> my profile

Friends/dcox2016.html
=> Added my webpage

Friends/TravelingMan.html
=> Add TravelingMan to the growing pile of friends

Friends/chetanag35.html
=> Add Friend

Friends/Mohammed532.html
Just wanted to thank you for this! New to github and I wanted to do something like this. You encouraged me to get into working with open sourced stuff so thank you!
=> Added myself, Mohammed532

Friends/carlosgub.html
=> friends html

Friends/AdnanMuhib.html
👋  hi...  You have a new friend request 😋
=> Add New Friend :ok_hand:

Friends/mayukh45.html
=> Added myself

Friends/Exorust.html
=> Added myself!

Friends/vaticori.html
Im a beginner who has a passion for coding, especially when it comes to the idea of making games! <3
=> Please accept me!

Friends/liooh.html
=>  My page html for make friends 

Friends/lucioleandro.html
=> this is mal pull.... request

Friends/ktopouzi.html
Hope this friendship never end! 😃
=> Added a new friend

Friends/pepper-seattle.html
Committing pepper-seattle.html
=> pepper-seattle friend html hacktober2018 commit

Friends/afro-code.html
=> Hello world

Friends/danherrera.html
=> Add friend Danilo

Friends/hilmibiya.html
=> add hilmi biya

Games/yuibun/index.html, Games/yuibun/main.css, Games/yuibun/main.js
=> added rock paper scissors game

Friends/Simply007.html
Your automatic detection did not detect button to my profile #189.
So I have added another one that is more visible. Hope the check pass.
=> Once again my profile card

Friends/sungk44.html
Hello!
I made an html file and added it in the friends folder :)
=> added-sunk44-in-friends

Friends/C-Bouthoorn.html
=> I love to meet new people!

Friends/JanuriDP.html
hey there, that is my work for week 1 hehe
if i can, i will participate on week 2 challange.
peace
=> add JanuriDP

Friends/darrenrector91.html
=> added html page

Friends/sr229.html
=> Senpai Raid notice me

contributors.md
i just adding my name to contrib file
=> adding my name

Games/gilann/index.html, Games/gilann/search.css
Type anything and search directly from Google.
=> Adding my awesome search box.

Games/tomerpacific/index.html, Games/tomerpacific/main.css, Games/tomerpacific/main.js
A simple snake game with two versions: Classic and Adventure.
Adventure lets you play the game where you can go through the walls.
References issue #227
=> Adding snake game

contributors.md
Added shannonmcook to list of Challenge Participants in the contributors.md file
=> Added myself to Challenge Participants

Games/Rahul-Vijay/index.html, Games/Rahul-Vijay/main.css, Games/Rahul-Vijay/main.js
A simple interactive color guessing game. The user gets a random RGB value and has to click on the required tile to guess the color. Referencing issue #227
=> Added a color guessing game

Games/connyheb/index.html, Games/connyheb/main.css, Games/connyheb/main.js, contributors.md
I added a little memory game and picked out ASCII art of animals to avoid needing pictures. Hope you like it :)
=> Added animal-themed memory game

contributors.md
I have taken part in week 2 challenge of building a game in HTML5.
=> Added myself to challenge participant's list

contributors.md
=> add the worst dev ever to the contributors list

Games/kumaran-14/index.html, Games/kumaran-14/main.css, Games/kumaran-14/main.js
HTML5 Canvas game.Use mouse to move character, click to shoot bullets.
=> obstacle game

Games/sohail764245/index.html, Games/sohail764245/main.css, Games/sohail764245/main.js, contributors.md
As per given rules and guidelines, I have added whack-a-mole game successfully.
=> added whack-a-mole game

Friends/shannonmcook.html
Add Shannon to yo' friendsbook :)
=> Added shannonmook.html file to FRIENDS folder

Games/fuj1n/index.html, Games/fuj1n/main.css, Games/fuj1n/main.js
=> Create game 'fuj1n'

Friends/ncplayz.html
=> give me my file back!!!

Games/muskan09/index.html, Games/muskan09/main.css, Games/muskan09/main.js
#227 
Please add my pixel art maker!
Thank you!
=> pixel art making game

Friends/kot83.html
=> Join To frieend list!!

Games/kakoon8/index.html, Games/kakoon8/main.css, Games/kakoon8/main.js
=> index.html

Friends/willianba.html, contributors.md
This PR has my friend page in the friends folder and my username in the contributors file 😄
=> New page in friends list

Friends/piyumidasanayaka.html
=> my first pull request

Games/cihantas/index.html, Games/cihantas/main.css, Games/cihantas/main.js
Hello everyone,
I added a game called Click The Odd I wrote this morning. IMO the game is self-explanatory. Have fun playing it. It's actually quite challenging sometimes.
=> Added my game called: Click The Odd

Friends/pavaniDamsara.html
…e can be diplayed.
Edit can be done with Github....To show the html page use the web browser.
=> Click this and add

contributors.md
Added myself to the contributors.md
=> Add mbain108 to contributors.md

contributors.md
=> Add myself to contributors

Games/shivansh-sopho/index.html
Its a very simple game where the user has to dodge the boards coming in its ways and should try to stay alive as long as possible.
=> Added my game "Dodge The Board"

Games/Rahul-Vijay/index.html, Games/saxenanamay/index.html, Games/saxenanamay/main.css, Games/saxenanamay/main.js
Previous entry of this game is not working due to incorrectly linked js and css files.
=> Added RGB color guessing game

Friends/harishr1308.html
=> New Friend: Harish

Games/Skilldeliver/index.html, Games/Skilldeliver/main.css, Games/Skilldeliver/main.js
You see 3 RGB values and 3 or 6 colour picks - depends on the mode. And you should try to guess what colour are these values.
=> Adding RGB game by Skilldeliver

Games/arch888/index.html, Games/arch888/main.css, Games/arch888/main.js, contributors.md
Adding a Hangman Web Game with Appropriate Rules
=> Adding Hangman Game

Games/harishr1308/index.html, Games/harishr1308/main.css, Games/harishr1308/main.js, contributors.md
=> New Game: Flappy Bird

Friends/SayuriRavihari.html
=> Check this and add

Games/jonsandg/index.html, Games/jonsandg/main.css, Games/jonsandg/main.js
Simple tic tac toe for two players
=> Created a tic-tac-toe 

BSoD/jasehub.html
=> BSOD as a html page

BSoD/crandalj.html
=> Add crandalj.html to BSOD

BSoD/Timmy.html, contributors.md
Here's my attempt at replicating a Windows 7 Blue Screen of Death with HTML & CSS.
=> My submission for the Week 3 challenge (BSoD)

BSoD/LevinFaber.html
I tried to recreate the Win10 BSoD for my submission. Thanks for the challenge.
=> BSoD implementation

Games/Archaeologist03/index.html, Games/Archaeologist03/main.css, Games/Archaeologist03/main.js
Small game with 9 fields where user by clicking on these trying to find.... well.. fat batmen.
=> Batmen game initalizer commit

contributors.md
I have added myself to the `contributors.md` file.
=> added myself to the contributors.md

BSoD/ScottEricRichardson.html
Scott Eric Richardson's BSOD html design based on Windows 98
=> BSOD for Windows 98

BSoD/sunpech.html
Added my BSoD page based off of IE browser error messages.
=> Added BSoD page.

Friends/tom-raley.html, contributors.md
Adding myself to contributors.md!
=> Add tom raley to contributors

Friends/tom-raley.html
Added my own HTML file to the Friends folder.
=> Added html file to friends

Friends/PhoenixJenn.html
=> Created new friend page

Friends/bartlomiej-przymus.html
It is a static html page with animation of white bouncing ball.
=> Created bartlomiej-przymus.html

BSoD/johneckert.html
added a bsod for hacktoberfest challenge
=> BSOD created

BSoD/capitanfindusfi.html
=> created my BSoD :(

BSoD/MansiAyer.html
Extremely simple BSoD in html.
=> MansiAyer.html

Friends/algoreriddum.html
I have added my own github username branch to the repo following all of the rules specified.
=> Algoreriddum branch

BSoD/vcodeearth.html
Created a new html with BSOD content.
=> BSOD by vcodeearth

Friends/hi-hi-ray.html
Hi!
I need more friends, so that's why i'm openning this PR. 
resolves #1
=> feat: add ray person. :leo: #1

Friends/leticiafaleia.html
hey, 
i'm letícia but you can call me let and i wanna be your friend.
xo, let
=> feat: add let person :droplet: #1

BSoD/keithieopia.html
My take on the classic Windows 95 BSoD that started the hatred of blue screens across the globe.
=> keithieopia's take on a Windows 95 BSoD

BSoD/NuMellow.html
=> Created a BSoD

BSoD/tomanistor.html
=> Created Blue Screen of Death

Friends/raviru.html
=> Check this and add 

Friends/techtolentino.html
=> Add new friend to /Friend
